#!/usr/bin/env python
"""Project management tools.

Usage:
    pm  [options] <command>

Command: init                  Initialize a project
         clean                 Remove obsolete files
         deliver               Deliver data
         compress              Compress data
         sbatch_helper         Create sbatch scripts
         statusdb              Connect to statusdb

Options: -c, --config          Config file [~/.pmrc]
"""

import os
import sys
import subprocess
import argparse

import pmtools.config


def init(args):
    print "In init"
    print args.config

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="", prog="pm")
    #parser = OptionParser()
    #parser.add_argument("-c", "--config",dest="config",  action="store", default=os.path.join(os.getenv("HOME"), ".pmrc"))

    parser.add_argument("-c", "--config",dest="config",  action="store", default=os.path.join(os.getenv("HOME"), ".pmrc"))
    # The commands 
    subparsers = parser.add_subparsers()
    parser_init = subparsers.add_parser("init", )
    parser_init.add_argument("-n", "--dry_run", dest="dry_run", action="store_true", default=False) 
    parser_init.set_defaults(func=init)

    ## Parse and call the function
    args = parser.parse_args()

    ## Check existence of config file
    if not os.path.exists(args.config):
        print >> sys.stderr, "[main] No such file %s" % args.config
        sys.exit()
        ##
    args.func(args)

