#!/usr/bin/env python
import os
import sys
from cement.core import foundation, handler, backend
from pm.core.config import config_defaults
from pm.cli import PmMainApp
from pm.cli.controller import PmBaseController
from pm.cli.admin import AdminController
from pm.cli.utils import UtilsController
from pm.cli.report import ReportController
#from pm.core.output import PmOutputHandler

CONFIGFILE=os.path.join(os.getenv("HOME"), ".pm2", "pm.yaml")
PLUGINDIR=os.path.join(os.getenv("HOME"), ".pm2", "plugins")
PLUGINCONFIGDIR=os.path.join(os.getenv("HOME"), ".pm2", "plugins.d")

# The project configuration should not be edited manually by the user
PROJECTCONFIGFILE=os.path.join(os.getenv("HOME"), ".pm2", "projects.yaml")

app = PmMainApp(base_controller = PmBaseController,
                config_defaults = config_defaults,
                #output_handler = PmOutputHandler, 
                config_files = [CONFIGFILE],
                extensions = [],
                plugin_dir = PLUGINDIR,
                plugin_config_dir = PLUGINCONFIGDIR,
                )

try:
    handler.register(AdminController)
    handler.register(UtilsController)
    handler.register(ReportController)
    app.setup()
    # Init project configuration
    app.config.parse_file(app._meta.project_config)
    
    with app.log.log_setup.applicationbound():
        app.run()
    app.render(app._output_data)
finally:
    app.close()
