#!/usr/bin/env python
import os
import sys
from cement.core import foundation, handler, backend
from pm.core.config import config_defaults
from pm.cli import PmMainApp
from pm.core.controller import PmBaseController
from pm.core.admin import AdminController
#from pm.core.output import PmOutputHandler

CONFIGFILE=os.path.join(os.getenv("HOME"), ".pm2", "pm.ini")
PLUGINDIR=os.path.join(os.getenv("HOME"), ".pm2", "plugins")
PLUGINCONFIGDIR=os.path.join(os.getenv("HOME"), ".pm2", "plugins.d")

# The project configuration should not be edited manually by the user
PROJECTCONFIGFILE=os.path.join(os.getenv("HOME"), ".pm2", "projects.json")

app = PmMainApp(base_controller = PmBaseController,
                config_defaults = config_defaults,
                #output_handler = PmOutputHandler, 
                config_files = [CONFIGFILE],
                extensions = [],
                plugin_dir = PLUGINDIR,
                plugin_config_dir = PLUGINCONFIGDIR,
                )

try:
    handler.register(AdminController)
    app.setup()
    with app.log.log_setup.applicationbound():
        try:
            app.config.parse_file(CONFIGFILE)
        except:
            app.log.warn("No config file %s; please create and set relevant config sections" % CONFIGFILE)
            sys.exit()
        app.run()
    app.render(app._output_data)
finally:
    app.close()
